spring:
  datasource:
    url: jdbc:h2:mem:test
    username: em
    password: pass
  h2:
    console:
      enabled: true
      path: /h2-console
github:
  host: https://api.github.com
  users: /users
